#!/usr/bin/python
print("""
// @(MSG_ORIGIN)
// @(MSG_EDIT_WARNING)

// Generated by _invoke.py
#include <Uno/ObjectModel.h>
#define CALL ((void(*)
#define ME )func)
#define T void*
#define A args

void uInvoke(const void* func, void** args, size_t count)
{
    switch (count)
    {
    default: U_THROW_IOORE();
""".strip())

for i in range(0, 49):
    sb = []
    sb.append("    case " + '{:>2}'.format(i) + ": CALL(")

    for j in range(i):
        if j > 0:
            sb.append(",")
        sb.append("T")

    sb.append(") ME(")

    for j in range(i):
        if j > 0:
            sb.append(",")
        sb.append("A[" + str(j) + "]")

    sb.append("); break;")
    line = ''.join(sb)

    while len(line) > 100:
        i = 100
        while line[i - 1].isalnum():
            i -= 1
        while line[i].isspace():
            i += 1
        print(line[:i])
        line = (" " * 13) + line[i:]

    print(line)

print("    }")
print("}")
