using System;
using System.IO;
using System.IO.Compression;

namespace Uno.Build.Packages.Feeds
{
    static class Extensions
    {
        public static void ExtractNupkg(this Stream f, string directory)
        {
            foreach (var e in new ZipArchive(f).Entries)
            {
                var name = Uri.UnescapeDataString(e.FullName.NativeToUnix());

                // Ignore useless files generated by NuGet
                switch (name)
                {
                    case "_rels/.rels":
                    case "[Content_Types].xml":
                        continue;
                    default:
                        if (name.StartsWith("packages/services/metadata/") ||
                            name.EndsWith(".nuspec"))
                            continue;
                        break;
                }

                var dst = Path.Combine(directory, name);
                var dir = Path.GetDirectoryName(dst);
                Directory.CreateDirectory(dir);
                e.ExtractToFile(dst, true);
            }
        }
    }
}